// THIS IS AUTOGENERATED CODE FOR VISION TARGETS WRITTEN IN MATLAB
// This file was auto-generated by Matlab under the supervision of Jacob Krucinski on 16-Mar-2019 at 11:39
#define H_min      0.0000
#define H_max      165.0000
#define S_min       0.0000
#define S_max      24.0551
#define V_min     223.0000
#define V_max     255.0000 
