// THIS IS AUTOGENERATED CODE FOR VISION TARGETS WRITTEN IN MATLAB
// This file was auto-generated by Matlab under the supervision of Jacob Krucinski on 19-Mar-2019 at 19:41
#define H_min      55.75
#define H_max      71.24
#define S_min      97.97
#define S_max     255.0000
#define V_min      86.0
#define V_max     201.0000