// THIS IS AUTOGENERATED CODE FOR VISION TARGETS WRITTEN IN MATLAB
// This file was auto-generated by Matlab under the supervision of Jacob Krucinski on 19-Mar-2019 at 19:41
#define H_min      56.1111
#define H_max      81.6514
#define S_min     128.8732
#define S_max     255.0000
#define V_min      34.0000
#define V_max     255.0000