// THIS IS AUTOGENERATED CODE FOR VISION TARGETS WRITTEN IN MATLAB
// This file was auto-generated by Matlab under the supervision of Jacob Krucinski on 06-Apr-2019 at 09:02
#define H_min      71.1111
#define H_max      94.0498
#define S_min     121.1429
#define S_max     254.6341
#define V_min     190.0000
#define V_max     255.0000
