// THIS IS AUTOGENERATED CODE FOR VISION TARGETS WRITTEN IN MATLAB
// This file was auto-generated by Matlab under the supervision of Jacob Krucinski on 19-Mar-2019 at 19:41
#define H_min      55.9
#define H_max      71.6
#define S_min      98.0
#define S_max     255.0000
#define V_min      86.0
#define V_max     201.0000